package matt.lyoko.lib;

public class ItemIds {

    public static int WEAPON_LYOKO_1_DEFAULT = 6081;
    public static int WEAPON_LYOKO_2_DEFAULT = 6082;
    public static int WEAPON_LYOKO_3_DEFAULT = 6083;
    public static int WEAPON_LYOKO_4_DEFAULT = 6084;
    public static int WEAPON_LYOKO_5_DEFAULT = 6085;
    public static int WEAPON_LYOKO_6_DEFAULT = 6086;
    public static int ITEM_SKID_DEFAULT = 6087;
    public static int ITEM_OVERBOARD_DEFAULT = 6088;
    public static int ITEM_QUANTUM_MATRIX_DEFAULT = 6089;
    public static int ITEM_QUANTUM_CONTAINMENT_CELL_DEFAULT = 6090;
    public static int LASER_SHOOTER_DEFAULT = 6091;
    public static int NOT_USED5_DEFAULT = 6092;
    public static int NOT_USED6_DEFAULT = 6093;
    public static int NOT_USED7_DEFAULT = 6094;
    public static int NOT_USED8_DEFAULT = 6095;
    public static int NOT_USED9_DEFAULT = 6096;
    public static int ITEM_LYOKO_URANIUM_DEFAULT = 6097;
    public static int ITEM_LYOKO_11_DEFAULT = 6098;
    public static int ITEM_LYOKO_12_DEFAULT = 6099;
    public static int ITEM_LYOKO_13_DEFAULT = 6100;
    public static int ITEM_LYOKO_14_DEFAULT = 6101;
    public static int ITEM_LYOKO_15_DEFAULT = 6102;
    public static int AELITA_ARMOR_HELMET_DEFAULT = 6103;
    public static int AELITA_ARMOR_CHEST_DEFAULT = 6104;
    public static int AELITA_ARMOR_PANTS_DEFAULT = 6105;
    public static int AELITA_ARMOR_BOOTS_DEFAULT = 6106;
    public static int ODD_ARMOR_HELMET_DEFAULT = 6107;
    public static int ODD_ARMOR_CHEST_DEFAULT = 6108;
    public static int ODD_ARMOR_PANTS_DEFAULT = 6109;
    public static int ODD_ARMOR_BOOTS_DEFAULT = 6110;
    public static int ULRICH_ARMOR_HELMET_DEFAULT = 6111;
    public static int ULRICH_ARMOR_CHEST_DEFAULT = 6112;
    public static int ULRICH_ARMOR_PANTS_DEFAULT = 6113;
    public static int ULRICH_ARMOR_BOOTS_DEFAULT = 6114;
    public static int YUMI_ARMOR_HELMET_DEFAULT = 6115;
    public static int YUMI_ARMOR_CHEST_DEFAULT = 6116;
    public static int YUMI_ARMOR_PANTS_DEFAULT = 6117;
    public static int YUMI_ARMOR_BOOTS_DEFAULT = 6118;
    public static int WILLIAM_ARMOR_HELMET_DEFAULT = 6119;
    public static int WILLIAM_ARMOR_CHEST_DEFAULT = 6120;
    public static int WILLIAM_ARMOR_PANTS_DEFAULT = 6121;
    public static int WILLIAM_ARMOR_BOOTS_DEFAULT = 6122;
    public static int DATA_FRAGMENT_DEFAULT = 6123;
    public static int ITEM_LYOKO_URANIUM_CELL_DEFAULT = 6124;
    public static int ITEM_LYOKO_DEPLETED_URANIUM_DEFAULT = 6125;
    
    public static int WEAPON_LYOKO_1;
    public static int WEAPON_LYOKO_2;
    public static int WEAPON_LYOKO_3;
    public static int WEAPON_LYOKO_4;
    public static int WEAPON_LYOKO_5;
    public static int WEAPON_LYOKO_6;
    public static int ITEM_SKID;
    public static int ITEM_OVERBOARD;
    public static int ITEM_QUANTUM_MATRIX;
    public static int ITEM_QUANTUM_CONTAINMENT_CELL;
    public static int LASER_SHOOTER;
    public static int NOT_USED5;
    public static int NOT_USED6;
    public static int NOT_USED7;
    public static int NOT_USED8;
    public static int NOT_USED9;
    public static int ITEM_LYOKO_URANIUM;
    public static int ITEM_LYOKO_11;
    public static int ITEM_LYOKO_12;
    public static int ITEM_LYOKO_13;
    public static int ITEM_LYOKO_14;
    public static int ITEM_LYOKO_15;
    public static int AELITA_ARMOR_HELMET;
    public static int AELITA_ARMOR_CHEST;
    public static int AELITA_ARMOR_PANTS;
    public static int AELITA_ARMOR_BOOTS;
    public static int ODD_ARMOR_HELMET;
    public static int ODD_ARMOR_CHEST;
    public static int ODD_ARMOR_PANTS;
    public static int ODD_ARMOR_BOOTS;
    public static int ULRICH_ARMOR_HELMET;
    public static int ULRICH_ARMOR_CHEST;
    public static int ULRICH_ARMOR_PANTS;
    public static int ULRICH_ARMOR_BOOTS;
    public static int YUMI_ARMOR_HELMET;
    public static int YUMI_ARMOR_CHEST;
    public static int YUMI_ARMOR_PANTS;
    public static int YUMI_ARMOR_BOOTS;
    public static int WILLIAM_ARMOR_HELMET;
    public static int WILLIAM_ARMOR_CHEST;
    public static int WILLIAM_ARMOR_PANTS;
    public static int WILLIAM_ARMOR_BOOTS;
    public static int DATA_FRAGMENT;
    public static int ITEM_LYOKO_URANIUM_CELL;
    public static int ITEM_LYOKO_DEPLETED_URANIUM;
}
